import Link from 'next/link';
import { Cta } from '@/components/cta';
import { services, getProjects } from '@/lib/content';

const serviceIllustrations: Record<string, string> = {
  automation: '/service-illustrations/automation.png',
  web: '/service-illustrations/web-development.png',
  ecommerce: '/service-illustrations/ecommerce.png',
  'custom-software': '/service-illustrations/custom-software.png',
};

export default async function Home() {
  const projects = (await getProjects()).slice(0, 2);

  return <main id="main">
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> DIGITAL ENGINEERING STUDIO</div><h1>Ideas are good.<br /><em>Working systems</em><br />are better.</h1><p>We design and build the digital tools behind better business—from automation and custom platforms to websites and online stores.</p><div className="hero-actions"><Link href="/contact" className="button button-primary">Tell us what you’re building <span aria-hidden="true">↗</span></Link><Link href="#services" className="text-link">Explore our services <span aria-hidden="true">↓</span></Link></div></div><div className="hero-art" aria-hidden="true"><div className="art-grid" /><div className="art-glow" /><div className="art-mark"><img src="/velaro-logo.png" alt="" /></div><div className="art-caption"><span>STRATEGY <b>→</b> DESIGN <b>→</b> BUILD</span><span>01 / 04</span></div></div></div><div className="shell hero-bottom"><span>Built around your business. Designed for what’s next.</span><span>SCROLL TO EXPLORE ↓</span></div></section>
    <section className="section intro-section"><div className="shell intro-grid"><div className="section-label">WHAT WE DO <span>01 / 03</span></div><div><h2>Technology should make your work <span className="accent-text">simpler.</span></h2><p>Too many businesses work around disconnected tools and digital experiences that no longer fit. We bring the pieces together with practical thinking, considered design, and solid engineering.</p></div></div></section>
    <section id="services" className="section services-section"><div className="shell"><div className="section-heading"><div><div className="section-label">OUR EXPERTISE <span>02 / 03</span></div><h2>Four ways to move forward.</h2></div><p>Start with the challenge. We’ll shape the right solution around it.</p></div><div className="services-list">{services.map((service) => <Link className="service-row" href={`/services/${service.slug}`} key={service.slug}><span className="service-number">{service.number}</span><div><h3>{service.name}</h3><p>{service.description}</p></div><img className="service-row-illustration" src={serviceIllustrations[service.slug]} alt="" /><span className="service-arrow" aria-hidden="true">↗</span></Link>)}</div></div></section>
    <section className="section approach-section"><div className="shell approach-grid"><div><div className="section-label">HOW WE WORK <span>03 / 03</span></div><h2>Clear thinking.<br />Confident delivery.</h2><p>Good work begins with the right questions. We define the problem, design the experience, build with care, and keep improving what matters.</p><Link href="/about" className="text-link">More about Velaro <span aria-hidden="true">↗</span></Link></div><div className="steps">{[['01', 'Understand', 'Get close to your goals, users, and current systems.'], ['02', 'Shape', 'Agree on priorities, scope, and a sensible path forward.'], ['03', 'Build', 'Design, develop, test, and launch the solution.'], ['04', 'Improve', 'Learn from use and evolve as your business grows.']].map(([number, title, description]) => <div className="step" key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div></div>)}</div></div></section>
    <section className="section work-section"><div className="shell"><div className="section-heading"><div><div className="section-label">SELECTED WORK</div><h2>Work that speaks for itself.</h2></div><Link href="/work" className="text-link">Explore our work <span aria-hidden="true">↗</span></Link></div>{projects.length ? <div className="project-grid">{projects.map((project) => <Link href={`/work/${project.slug}`} className="project-card" key={project.slug}><div className="project-visual">{project.image ? <img src={project.image} alt={project.imageAlt || project.title} /> : <span>{project.title.slice(0, 1)}</span>}</div><div className="project-meta"><span>{project.service}</span><span>{project.year}</span></div><h3>{project.title} <span aria-hidden="true">↗</span></h3><p>{project.summary}</p></Link>)}</div> : <div className="work-empty"><span className="work-empty-mark">V<span>.</span></span><div><h3>New work is on the way.</h3><p>We’re preparing case studies that show the thinking and outcomes behind our projects. Have a challenge of your own? We’d like to hear it.</p><Link href="/contact" className="text-link">Talk to us <span aria-hidden="true">↗</span></Link></div></div>}</div></section>
    <Cta />
  </main>;
}
